//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Commons.System.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bridge.Commons.System.Resources.BaseErrors", typeof(BaseErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade não encontrada.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo atingiu o tamanho máximo.
        /// </summary>
        public static string FieldMaximumLength {
            get {
                return ResourceManager.GetString("FieldMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo deve ser preenchido.
        /// </summary>
        public static string FieldMustBeFilled {
            get {
                return ResourceManager.GetString("FieldMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser preenchido.
        /// </summary>
        public static string FieldMustBeFilledFormat {
            get {
                return ResourceManager.GetString("FieldMustBeFilledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo está fora do intervalo.
        /// </summary>
        public static string FieldOutOfRange {
            get {
                return ResourceManager.GetString("FieldOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo está com tamanho incorreto.
        /// </summary>
        public static string FieldWrongLength {
            get {
                return ResourceManager.GetString("FieldWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo não corresponde ao tipo.
        /// </summary>
        public static string FieldWrongType {
            get {
                return ResourceManager.GetString("FieldWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso proibido. Não há permissão para executar a requisição solicitada.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta é uma conexão apenas leitura. Por favor, use uma context de escrita (BaseWriteContext).
        /// </summary>
        public static string InvalidOperationOnReadOnlyConnection {
            get {
                return ResourceManager.GetString("InvalidOperationOnReadOnlyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro inválido.
        /// </summary>
        public static string InvalidRequestParameter {
            get {
                return ResourceManager.GetString("InvalidRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros inválidos.
        /// </summary>
        public static string InvalidRequestParameters {
            get {
                return ResourceManager.GetString("InvalidRequestParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
